DROP TABLE t1 CASCADE CONSTRAINTS;

CREATE TABLE t1 (
    a1 varchar2(10) primary key
);

ALTER TABLE t1 ADD a2 varchar2(5);

ALTER TABLE t1 MODIFY a2 varchar2(10);

ALTER TABLE t1 MODIFY a2 number(5);

ALTER TABLE t1 MODIFY a2 number(10, 5);

ALTER TABLE t1 MODIFY a2 not null ;

ALTER TABLE t1 MODIFY a2 null ;

ALTER TABLE t1 MODIFY a2 DEFAULT 1;

ALTER TABLE t1 MODIFY a2 DEFAULT null;

ALTER TABLE t1 ADD CONSTRAINT t1_unique_a2 UNIQUE(a2);

ALTER TABLE t1 DROP CONSTRAINT t1_unique_a2;

ALTER TABLE t1 ADD CONSTRAINT t1_range_check_a2 CHECK (a2 BETWEEN 1 AND 10);

ALTER TABLE t1 DROP CONSTRAINT t1_range_check_a2;
ALTER TABLE t1 ADD CONSTRAINT t1_range_check_a2 CHECK (a2 BETWEEN 1 AND 5);

ALTER TABLE t1 ADD CONSTRAINT t1_in_set_check CHECK (a2 in (1,2,3,4,5));

DROP TABLE t2 CASCADE CONSTRAINTS;

CREATE TABLE t2(
    b1 number(10,5) PRIMARY KEY
);

ALTER TABLE t1 ADD CONSTRAINT FK_a2_b1 FOREIGN KEY(a2) REFERENCES t2(b1);

INSERT INTO t1 (a1, a2) VALUES ('pitt01', 1);

ALTER TABLE t1 ADD CONSTRAINT unique_a2_a2 UNIQUE(a1, a2);

ALTER TABLE t1 DROP COLUMN a2;

ALTER TABLE t1 DROP COLUMN a2 CASCADE CONSTRAINTS;