-- Every time that the program starts you need to initialize
-- all the above tables with sample data from the last four Olympic games (Beijing, Paris, London, Rio)
-- for 6 events (3 atomic and 3 team events) and 6 countries (which have won medals). Note that this
-- script will help you validate the integrity constraints and triggers.

INSERT INTO USER_ROLE values(1, 'Guest');
INSERT INTO USER_ROLE values(2, 'Organizer');
INSERT INTO USER_ROLE values(3, 'Coach');

INSERT INTO USER_ACCOUNT values(1, 'guest', 'GUEST', 1, null);
INSERT INTO USER_ACCOUNT values(2, 'Carlos Arthur Nuzman', 'Rio', 2, null);
INSERT INTO USER_ACCOUNT values(3, 'Gianna Angelopoulos', 'Athens', 2, null);
INSERT INTO USER_ACCOUNT values(4, 'Hu Jintao', 'Beijing', 2, null);
INSERT INTO USER_ACCOUNT values(5, 'Sebastian Coe', 'London', 2, null);

INSERT INTO OLYMPICS values(1, 'XXXI', 'Rio de Janeiro', '05-Aug-16', '21-Aug-16', 'https://www.olympic.org/rio-2016');
INSERT INTO OLYMPICS values(2, 'XXX', 'London', '27-Jul-12', '12-Aug-12', 'https://www.olympic.org/london-2012');
INSERT INTO OLYMPICS values(3, 'XXIX', 'Beijing', '08-Aug-08', '24-Aug-08', 'https://www.olympic.org/beijing-2008');
INSERT INTO OLYMPICS values(4, 'XXVIII', 'Athens', '13-Aug-04', '29-Aug-04', 'https://www.olympic.org/athens-2004');

INSERT INTO SPORT values(1, '400M Dash', 'a sprinting event around the track once', '6-Apr-1896', 1);
INSERT INTO SPORT values(2, '800M Dash', 'run two laps of the track', '6-Apr-1896', 1);
INSERT INTO SPORT values(3, '100M Dash', '100 meter run', '6-Apr-1896', 1);
INSERT INTO SPORT values(4, '4x100M Relay', 'four people sprint around the track with and pass a baton', '6-Apr-1896', 4);
INSERT INTO SPORT values(5, '4x400M Relay', 'four people do one lap around the track each', '6-Apr-1896', 4);
INSERT INTO SPORT values(6, 'Basketball', 'two teams shoot a ball into a hoop', '6-Apr-1936', 5);

INSERT INTO MEDAL (medal_id, medal_title, points) values (1, 'gold', 5);
INSERT INTO MEDAL (medal_id, medal_title, points) values (2, 'silver', 3);
INSERT INTO MEDAL (medal_id, medal_title, points) values (3, 'bronze', 1);


---

INSERT INTO USER_ROLE values(1, 'guest');
INSERT INTO USER_ROLE values(2, 'organizer');
INSERT INTO USER_ROLE values(3, 'coach');


INSERT INTO USER_ACCOUNT values(0, 'guest', 'GUEST', 1, null);
INSERT INTO USER_ACCOUNT values(1, 'Carlos Arthur Nuzman', 'Rio', 2, null);
INSERT INTO USER_ACCOUNT values(2, 'Gianna Angelopoulos', 'Athens', 2, null);
INSERT INTO USER_ACCOUNT values(3, 'Hu Jintao', 'Beijing', 2, null);
INSERT INTO USER_ACCOUNT values(4, 'Sebastian Coe', 'London', 2, null);
INSERT INTO USER_ACCOUNT values(5, 'Paul Hadzor', 'ph', 3, null);
INSERT INTO USER_ACCOUNT values(6, 'Tom Crouse', 'tc', 3, null);
INSERT INTO USER_ACCOUNT values(7, 'Nicole Jones', 'nj', 3, null);
INSERT INTO USER_ACCOUNT values(8, 'Michael Yang', 'my', 3, null);
INSERT INTO USER_ACCOUNT values(9, 'Edward Burgess', 'eb', 3, null);
INSERT INTO USER_ACCOUNT values(10, 'Andrew Li', 'al', 3, null);
INSERT INTO USER_ACCOUNT values(11, 'Bobby Eppleman', 'be ', 3, null);
INSERT INTO USER_ACCOUNT values(12, 'Tim Pappas', 'tp', 3, null);
INSERT INTO USER_ACCOUNT values(13, 'Karin Hufnagl', 'kh', 3, null);
INSERT INTO USER_ACCOUNT values(14, 'Zachary Fifer', 'zf', 3, null);


INSERT INTO OLYMPICS values(3, 'XXXI', 'Rio de Janeiro', '05-Aug-16', '21-Aug-16', 'https://www.olympic.org/rio-2016');
INSERT INTO OLYMPICS values(2, 'XXX', 'London', '27-Jul-12', '12-Aug-12', 'https://www.olympic.org/london-2012');
INSERT INTO OLYMPICS values(1, 'XXIX', 'Beijing', '08-Aug-08', '24-Aug-08', 'https://www.olympic.org/beijing-2008');
INSERT INTO OLYMPICS values(0, 'XXVIII', 'Athens', '13-Aug-04', '29-Aug-04', 'https://www.olympic.org/athens-2004');


INSERT INTO COUNTRY values(0, 'Jamaica', 'JAM');
INSERT INTO COUNTRY values(1, 'United', 'States');
INSERT INTO COUNTRY values(2, 'Kenya', 'KEN');
INSERT INTO COUNTRY values(3, 'Grenada', 'GRN');
INSERT INTO COUNTRY values(4, 'Trinidad', 'and');
INSERT INTO COUNTRY values(5, 'Botswana', 'BOT');
INSERT INTO COUNTRY values(6, 'Brunei', 'BRN');
INSERT INTO COUNTRY values(7, 'Great', 'Britian');
INSERT INTO COUNTRY values(8, 'Afghanistan', 'AFG');
INSERT INTO COUNTRY values(9, 'Albania', 'ALB');
INSERT INTO COUNTRY values(10, 'Algeria', 'ALG');
INSERT INTO COUNTRY values(11, 'Andorra', 'AND');
INSERT INTO COUNTRY values(12, 'Angola', 'ANG');
INSERT INTO COUNTRY values(13, 'Antigua', 'and');
INSERT INTO COUNTRY values(14, 'Argentina', 'ARG');
INSERT INTO COUNTRY values(15, 'Armenia', 'ARM');
INSERT INTO COUNTRY values(16, 'Aruba', 'ARU');
INSERT INTO COUNTRY values(17, 'American', 'Samoa');
INSERT INTO COUNTRY values(18, 'Australia', 'AUS');
INSERT INTO COUNTRY values(19, 'Austria', 'AUT');
INSERT INTO COUNTRY values(20, 'Azerbaijan', 'AZE');
INSERT INTO COUNTRY values(21, 'Bahamas', 'BAH');
INSERT INTO COUNTRY values(22, 'Bangladesh', 'BAN');
INSERT INTO COUNTRY values(23, 'Barbados', 'BAR');
INSERT INTO COUNTRY values(24, 'Burundi', 'BDI');
INSERT INTO COUNTRY values(25, 'Belgium', 'BEL');
INSERT INTO COUNTRY values(26, 'Benin', 'BEN');
INSERT INTO COUNTRY values(27, 'Bermuda', 'BER');
INSERT INTO COUNTRY values(28, 'Bhutan', 'BHU');
INSERT INTO COUNTRY values(29, 'Bosnia', 'BIH');
INSERT INTO COUNTRY values(30, 'Belize', 'BIZ');
INSERT INTO COUNTRY values(31, 'Belarus', 'BLR');
INSERT INTO COUNTRY values(32, 'Bolivia', 'BOL');
INSERT INTO COUNTRY values(33, 'Brazil', 'BRA');
INSERT INTO COUNTRY values(34, 'Brunei', 'BRU');
INSERT INTO COUNTRY values(35, 'Bulgaria', 'BUL');
INSERT INTO COUNTRY values(36, 'Burkina', 'Faso');
INSERT INTO COUNTRY values(37, 'Central', 'African');
INSERT INTO COUNTRY values(38, 'Cambodia', 'CAM');
INSERT INTO COUNTRY values(39, 'Canada', 'CAN');
INSERT INTO COUNTRY values(40, 'Cayman', 'Islands');
INSERT INTO COUNTRY values(41, 'Republic', 'of');
INSERT INTO COUNTRY values(42, 'Chad', 'CHA');
INSERT INTO COUNTRY values(43, 'Chile', 'CHI');
INSERT INTO COUNTRY values(44, 'China', 'CHN');
INSERT INTO COUNTRY values(45, 'Ivory', 'Coast');
INSERT INTO COUNTRY values(46, 'Cameroon', 'CMR');
INSERT INTO COUNTRY values(47, 'Dem', 'Rep');
INSERT INTO COUNTRY values(48, 'Cook', 'Islands');
INSERT INTO COUNTRY values(49, 'Colombia', 'COL');
INSERT INTO COUNTRY values(50, 'Comoros', 'COM');
INSERT INTO COUNTRY values(51, 'Cape', 'Verde');
INSERT INTO COUNTRY values(52, 'Costa', 'Rica');
INSERT INTO COUNTRY values(53, 'Croatia', 'CRO');
INSERT INTO COUNTRY values(54, 'Cuba', 'CUB');
INSERT INTO COUNTRY values(55, 'Cyprus', 'CYP');
INSERT INTO COUNTRY values(56, 'Czech', 'Republic');
INSERT INTO COUNTRY values(57, 'Denmark', 'DEN');
INSERT INTO COUNTRY values(58, 'Djibouti', 'DJI');
INSERT INTO COUNTRY values(59, 'Dominica', 'DMA');
INSERT INTO COUNTRY values(60, 'Dominican', 'Republic');
INSERT INTO COUNTRY values(61, 'Ecuador', 'ECU');
INSERT INTO COUNTRY values(62, 'Egypt', 'EGY');
INSERT INTO COUNTRY values(63, 'Eritrea', 'ERI');
INSERT INTO COUNTRY values(64, 'El', 'Salvador');
INSERT INTO COUNTRY values(65, 'Spain', 'ESP');
INSERT INTO COUNTRY values(66, 'Estonia', 'EST');
INSERT INTO COUNTRY values(67, 'Ethiopia', 'ETH');
INSERT INTO COUNTRY values(68, 'Fiji', 'FIJ');
INSERT INTO COUNTRY values(69, 'Finland', 'FIN');
INSERT INTO COUNTRY values(70, 'France', 'FRA');
INSERT INTO COUNTRY values(71, 'Federated', 'Micronesia');
INSERT INTO COUNTRY values(72, 'Gabon', 'GAB');
INSERT INTO COUNTRY values(73, 'The', 'Gambia');
INSERT INTO COUNTRY values(74, 'Guinea-Bissau', 'GBS');
INSERT INTO COUNTRY values(75, 'Georgia', 'GEO');
INSERT INTO COUNTRY values(76, 'Equatorial', 'Guinea');
INSERT INTO COUNTRY values(77, 'Germany', 'GER');
INSERT INTO COUNTRY values(78, 'Ghana', 'GHA');
INSERT INTO COUNTRY values(79, 'Greece', 'GRE');
INSERT INTO COUNTRY values(80, 'Guatemala', 'GUA');
INSERT INTO COUNTRY values(81, 'Guinea', 'GUI');
INSERT INTO COUNTRY values(82, 'Guam', 'GUM');
INSERT INTO COUNTRY values(83, 'Guyana', 'GUY');
INSERT INTO COUNTRY values(84, 'Haiti', 'HAI');
INSERT INTO COUNTRY values(85, 'Hong', 'Kong,');
INSERT INTO COUNTRY values(86, 'Honduras', 'HON');
INSERT INTO COUNTRY values(87, 'Hungary', 'HUN');
INSERT INTO COUNTRY values(88, 'Indonesia', 'INA');
INSERT INTO COUNTRY values(89, 'India', 'IND');
INSERT INTO COUNTRY values(90, 'Iran', 'IRI');
INSERT INTO COUNTRY values(91, 'Ireland', 'IRL');
INSERT INTO COUNTRY values(92, 'Iraq', 'IRQ');
INSERT INTO COUNTRY values(93, 'Iceland', 'ISL');
INSERT INTO COUNTRY values(94, 'Israel', 'ISR');
INSERT INTO COUNTRY values(95, 'Virgin', 'Islands');
INSERT INTO COUNTRY values(96, 'Italy', 'ITA');
INSERT INTO COUNTRY values(97, 'Brit', 'Virgin');
INSERT INTO COUNTRY values(98, 'Jordan', 'JOR');
INSERT INTO COUNTRY values(99, 'Japan', 'JPN');
INSERT INTO COUNTRY values(100, 'Kazakhstan', 'KAZ');
INSERT INTO COUNTRY values(101, 'Kyrgyzstan', 'KGZ');
INSERT INTO COUNTRY values(102, 'Kiribati', 'KIR');
INSERT INTO COUNTRY values(103, 'South', 'Korea');
INSERT INTO COUNTRY values(104, 'Kosovo', 'KOS');
INSERT INTO COUNTRY values(105, 'Saudi', 'Arabia');
INSERT INTO COUNTRY values(106, 'Kuwait', 'KUW');
INSERT INTO COUNTRY values(107, 'Laos', 'LAO');
INSERT INTO COUNTRY values(108, 'Latvia', 'LAT');
INSERT INTO COUNTRY values(109, 'Libya', 'LBA');
INSERT INTO COUNTRY values(110, 'Lebanon', 'LBN');
INSERT INTO COUNTRY values(111, 'Liberia', 'LBR');
INSERT INTO COUNTRY values(112, 'Saint', 'Lucia');
INSERT INTO COUNTRY values(113, 'Lesotho', 'LES');
INSERT INTO COUNTRY values(114, 'Liechtenstein', 'LIE');
INSERT INTO COUNTRY values(115, 'Lithuania', 'LTU');
INSERT INTO COUNTRY values(116, 'Luxembourg', 'LUX');
INSERT INTO COUNTRY values(117, 'Madagascar', 'MAD');
INSERT INTO COUNTRY values(118, 'Morocco', 'MAR');
INSERT INTO COUNTRY values(119, 'Malaysia', 'MAS');
INSERT INTO COUNTRY values(120, 'Malawi', 'MAW');
INSERT INTO COUNTRY values(121, 'Moldova', 'MDA');
INSERT INTO COUNTRY values(122, 'Maldives', 'MDV');
INSERT INTO COUNTRY values(123, 'Mexico', 'MEX');
INSERT INTO COUNTRY values(124, 'Mongolia', 'MGL');
INSERT INTO COUNTRY values(125, 'Marshall', 'Islands');
INSERT INTO COUNTRY values(126, 'North', 'Macedonia');
INSERT INTO COUNTRY values(127, 'Mali', 'MLI');
INSERT INTO COUNTRY values(128, 'Malta', 'MLT');
INSERT INTO COUNTRY values(129, 'Montenegro', 'MNE');
INSERT INTO COUNTRY values(130, 'Monaco', 'MON');
INSERT INTO COUNTRY values(131, 'Mozambique', 'MOZ');
INSERT INTO COUNTRY values(132, 'Mauritius', 'MRI');
INSERT INTO COUNTRY values(133, 'Mauritania', 'MTN');
INSERT INTO COUNTRY values(134, 'Myanmar', 'MYA');
INSERT INTO COUNTRY values(135, 'Namibia', 'NAM');
INSERT INTO COUNTRY values(136, 'Nicaragua', 'NCA');
INSERT INTO COUNTRY values(137, 'Netherlands', 'NED');
INSERT INTO COUNTRY values(138, 'Nepal', 'NEP');
INSERT INTO COUNTRY values(139, 'Nigeria', 'NGR');
INSERT INTO COUNTRY values(140, 'Niger', 'NIG');
INSERT INTO COUNTRY values(141, 'Norway', 'NOR');
INSERT INTO COUNTRY values(142, 'Nauru', 'NRU');
INSERT INTO COUNTRY values(143, 'New', 'Zealand');
INSERT INTO COUNTRY values(144, 'Oman', 'OMA');
INSERT INTO COUNTRY values(145, 'Pakistan', 'PAK');
INSERT INTO COUNTRY values(146, 'Panama', 'PAN');
INSERT INTO COUNTRY values(147, 'Paraguay', 'PAR');
INSERT INTO COUNTRY values(148, 'Peru', 'PER');
INSERT INTO COUNTRY values(149, 'Philippines', 'PHI');
INSERT INTO COUNTRY values(150, 'Palestine', 'PLE');
INSERT INTO COUNTRY values(151, 'Palau', 'PLW');
INSERT INTO COUNTRY values(152, 'Papua', 'New');
INSERT INTO COUNTRY values(153, 'Poland', 'POL');
INSERT INTO COUNTRY values(154, 'Portugal', 'POR');
INSERT INTO COUNTRY values(155, 'North', 'Korea');
INSERT INTO COUNTRY values(156, 'Puerto', 'Rico');
INSERT INTO COUNTRY values(157, 'Qatar', 'QAT');
INSERT INTO COUNTRY values(158, 'Romania', 'ROU');
INSERT INTO COUNTRY values(159, 'South', 'Africa');
INSERT INTO COUNTRY values(160, 'Russia', 'RUS');
INSERT INTO COUNTRY values(161, 'Rwanda', 'RWA');
INSERT INTO COUNTRY values(162, 'Samoa', 'SAM');
INSERT INTO COUNTRY values(163, 'Senegal', 'SEN');
INSERT INTO COUNTRY values(164, 'Seychelles', 'SEY');
INSERT INTO COUNTRY values(165, 'Singapore', 'SGP');
INSERT INTO COUNTRY values(166, 'Saint', 'Kitts');
INSERT INTO COUNTRY values(167, 'Sierra', 'Leone');
INSERT INTO COUNTRY values(168, 'Slovenia', 'SLO');
INSERT INTO COUNTRY values(169, 'San', 'Marino');
INSERT INTO COUNTRY values(170, 'Solomon', 'Islands');
INSERT INTO COUNTRY values(171, 'Somalia', 'SOM');
INSERT INTO COUNTRY values(172, 'Serbia', 'SRB');
INSERT INTO COUNTRY values(173, 'Sri', 'Lanka');
INSERT INTO COUNTRY values(174, 'South', 'Sudan');
INSERT INTO COUNTRY values(175, 'São', 'Tomé');
INSERT INTO COUNTRY values(176, 'Sudan', 'SUD');
INSERT INTO COUNTRY values(177, 'Switzerland', 'SUI');
INSERT INTO COUNTRY values(178, 'Suriname', 'SUR');
INSERT INTO COUNTRY values(179, 'Slovakia', 'SVK');
INSERT INTO COUNTRY values(180, 'Sweden', 'SWE');
INSERT INTO COUNTRY values(181, 'Swaziland', 'SWZ');
INSERT INTO COUNTRY values(182, 'Syria', 'SYR');
INSERT INTO COUNTRY values(183, 'Tanzania', 'TAN');
INSERT INTO COUNTRY values(184, 'Tonga', 'TGA');
INSERT INTO COUNTRY values(185, 'Thailand', 'THA');
INSERT INTO COUNTRY values(186, 'Tajikistan', 'TJK');
INSERT INTO COUNTRY values(187, 'Turkmenistan', 'TKM');
INSERT INTO COUNTRY values(188, 'East', 'Timor');
INSERT INTO COUNTRY values(189, 'Togo', 'TOG');
INSERT INTO COUNTRY values(190, 'Chinese', 'Taipei');
INSERT INTO COUNTRY values(191, 'Tunisia', 'TUN');
INSERT INTO COUNTRY values(192, 'Turkey', 'TUR');
INSERT INTO COUNTRY values(193, 'Tuvalu', 'TUV');
INSERT INTO COUNTRY values(194, 'United', 'Arab');
INSERT INTO COUNTRY values(195, 'Uganda', 'UGA');
INSERT INTO COUNTRY values(196, 'Ukraine', 'UKR');
INSERT INTO COUNTRY values(197, 'Uruguay', 'URU');
INSERT INTO COUNTRY values(198, 'Uzbekistan', 'UZB');
INSERT INTO COUNTRY values(199, 'Vanuatu', 'VAN');
INSERT INTO COUNTRY values(200, 'Venezuela', 'VEN');
INSERT INTO COUNTRY values(201, 'Vietnam', 'VIE');
INSERT INTO COUNTRY values(202, 'Saint', 'Vincent');
INSERT INTO COUNTRY values(203, 'Yemen', 'YEM');
INSERT INTO COUNTRY values(204, 'Zambia', 'ZAM');
INSERT INTO COUNTRY values(205, 'Zimbabwe', 'ZIM');

INSERT INTO SPORT values(1, '400M', 'Run 400 meters across the track', '06-Apr-96', 1);
INSERT INTO SPORT values(2, '800M', 'Run two laps across the track', '06-Apr-96', 1);
INSERT INTO SPORT values(3, '100M', 'Run 100 meters on the track', '06-Apr-96', 1);
INSERT INTO SPORT values(4, '4x1', 'A relay, where people pass a baton', '06-Apr-96', 4);
INSERT INTO SPORT values(5, '4x4', 'A relay, where people complete a mile in total', '06-Apr-96', 4);
INSERT INTO SPORT values(6, 'Basketball', 'A game where people shoot a ball into a hoop', '06-Apr-36', 5);


INSERT INTO VENUE values(0, 0, 'Olympic Stadium of Athens', 1);
INSERT INTO VENUE values(1, 0, 'Hellinikon Indoor Arena', 1);
INSERT INTO VENUE values(2, 1, 'Beijing National Stadium', 1);
INSERT INTO VENUE values(3, 1, 'Wukesong Indoor Stadium', 1);
INSERT INTO VENUE values(4, 2, 'London Stadium', 1);
INSERT INTO VENUE values(5, 2, 'Basketball Arena', 1);
INSERT INTO VENUE values(6, 3, 'Estadio Olimpico Nilton Santos', 1);
INSERT INTO VENUE values(7, 3, 'Caropica Arena 1', 1);


INSERT INTO EVENT values(0, 1, 0, 'm', null);
INSERT INTO EVENT values(1, 2, 2, 'f', null);
INSERT INTO EVENT values(2, 3, 4, 'm', null);
INSERT INTO EVENT values(3, 4, 6, 'f', null);
INSERT INTO EVENT values(4, 5, 6, 'm', null);
INSERT INTO EVENT values(5, 6, 5, 'm', null);
INSERT INTO EVENT values(6, 1, 0, 'm', null);
INSERT INTO EVENT values(7, 1, 0, 'm', null);
INSERT INTO EVENT values(8, 1, 0, 'm', null);
INSERT INTO EVENT values(9, 1, 0, 'm', null);
INSERT INTO EVENT values(10, 2, 0, 'm', null);
INSERT INTO EVENT values(11, 2, 0, 'm', null);


INSERT INTO MEDAL values(1, 'gold', 5);
INSERT INTO MEDAL values(2, 'silver', 3);
INSERT INTO MEDAL values(3, 'bronze', 1);


INSERT INTO PARTICIPANT values(0, 'Usain', 'Bolt', 'Jamaican', 'Sherwood Content', '21-Aug-86');
INSERT INTO PARTICIPANT values(1, 'Yohan', 'Blake', 'Jamaican', 'St. James', '26-Dec-89');
INSERT INTO PARTICIPANT values(2, 'Justin', 'Gatlin', 'American', 'Brooklyn', '10-Feb-82');
INSERT INTO PARTICIPANT values(3, 'Tyson ', 'Gay', 'American', 'Lexington', '09-Aug-82');
INSERT INTO PARTICIPANT values(4, 'Ryan ', 'Bailey', 'American', 'Portland', '13-Apr-89');
INSERT INTO PARTICIPANT values(5, 'Pamela ', 'Jelimo', 'Kenyan', 'Nandi District', '05-Dec-89');
INSERT INTO PARTICIPANT values(6, 'Jeremy', 'Wariner', 'American', 'McKinney', '31-Jan-84');
INSERT INTO PARTICIPANT values(7, 'Kevin', 'Durant', 'American', 'Washington DC', '29-Sep-88');
INSERT INTO PARTICIPANT values(8, 'Carmelo', 'Anthony', 'American', 'Brooklyn', '29-May-84');
INSERT INTO PARTICIPANT values(9, 'Kyrie', 'Irving', 'American', 'Melbourne', '23-Mar-92');
INSERT INTO PARTICIPANT values(10, 'Klay', 'Thompson', 'American', 'Los Angeles', '08-Feb-90');
INSERT INTO PARTICIPANT values(11, 'Demarcus', 'Cousins', 'American', 'Mobile', '13-Aug-90');
INSERT INTO PARTICIPANT values(12, 'Allyson', 'Felix', 'American', 'Los Angeles', '18-Nov-85');
INSERT INTO PARTICIPANT values(13, 'English', 'Gardner', 'American', 'Philadelphia', '22-Apr-92');
INSERT INTO PARTICIPANT values(14, 'Tianna', 'Bartoletta', 'American', 'Elyria', '30-Aug-85');
INSERT INTO PARTICIPANT values(15, 'Tori', 'Bowie', 'American', 'Sand Hill', '27-Aug-90');
INSERT INTO PARTICIPANT values(16, 'Lashawn', 'Merritt', 'American', 'Portsmouth', '27-Jun-86');
INSERT INTO PARTICIPANT values(17, 'Gil', 'Roberts', 'American', 'Oklahoma City', '15-Mar-89');
INSERT INTO PARTICIPANT values(18, 'Tony ', 'McQuay', 'American ', 'West Palm Beach', '16-Apr-90');
INSERT INTO PARTICIPANT values(19, 'Arman', 'Hall', 'American', 'Gainesville', '12-Feb-94');
INSERT INTO PARTICIPANT values(20, 'Paul', 'Hadzor', 'Jamaican', 'Pittsburgh', '06-Feb-60');
INSERT INTO PARTICIPANT values(21, 'Tom ', 'Crouse', 'American', 'Philadelphia', '17-Sep-75');
INSERT INTO PARTICIPANT values(22, 'Nicole', 'Jones', 'American', 'Malvern', '22-Nov-72');
INSERT INTO PARTICIPANT values(23, 'Michael', 'Yang', 'American', 'Paoli', '05-Jul-95');
INSERT INTO PARTICIPANT values(24, 'Edward', 'Burgess', 'American', 'Bryn Mawr', '26-Jun-92');
INSERT INTO PARTICIPANT values(25, 'Andrew', 'Li', 'American', 'Exton', '15-Aug-90');
INSERT INTO PARTICIPANT values(26, 'Bobby ', 'Eppleman', 'American', 'King of Prussia', '21-Feb-87');
INSERT INTO PARTICIPANT values(27, 'Tim', 'Pappas', 'American', 'Philadelphia', '13-Jan-80');
INSERT INTO PARTICIPANT values(28, 'Karin', 'Hufnagl', 'American', 'Glen Mills', '21-Mar-75');
INSERT INTO PARTICIPANT values(29, 'Zachary', 'Fifer', 'American', 'Newtown Square', '11-Jan-85');
INSERT INTO PARTICIPANT values(30, 'Wayde', 'Van Niekerk', 'South African', 'Cape Town  ', '15-Jul-92');
INSERT INTO PARTICIPANT values(31, 'Kirani', 'James', 'Grenada', 'Gouyave', '01-Sep-92');
INSERT INTO PARTICIPANT values(32, 'Machel', 'Cedenio', 'Trinidad', 'San Fernado', '06-Sep-95');
INSERT INTO PARTICIPANT values(33, 'Karabo', 'Sibanda', 'Botswana', 'Francistown', '02-Jul-98');
INSERT INTO PARTICIPANT values(34, 'Ali Khamis', 'Khamis', 'Bahrain', 'Manama', '30-Jun-95');
INSERT INTO PARTICIPANT values(35, 'Bralon', 'Taplin', 'Grenada', 'St. Georges', '08-May-92');
INSERT INTO PARTICIPANT values(36, 'Matthew', 'Hudson-Smith', 'Britsih', 'Wolverhampton', '26-Oct-94');
INSERT INTO PARTICIPANT values(37, 'Brianna', 'Bismark-Petit', 'South African', 'Cape Town  ', '02-Feb-50');
INSERT INTO PARTICIPANT values(38, 'Alex', 'Siaton', 'American', 'Philadelphia', '24-Jan-51');
INSERT INTO PARTICIPANT values(39, 'Luke', 'Lasure', 'Great Britain', 'London', '12-Nov-86');
INSERT INTO PARTICIPANT values(40, 'Emma ', 'Iacobucci', 'American', 'Madison', '24-Jan-51');
INSERT INTO PARTICIPANT values(41, 'Nate', 'Beebe', 'American', 'San Antonio', '22-May-52');
INSERT INTO PARTICIPANT values(42, 'Shane ', 'Johnston', 'American', 'Miami', '01-Jul-53');
INSERT INTO PARTICIPANT values(43, 'Katie', 'Ford', 'American', 'Tucson', '12-Jun-57');
INSERT INTO PARTICIPANT values(44, 'Jack', 'Barron', 'American', 'Honolulu', '01-Nov-60');
INSERT INTO PARTICIPANT values(45, 'Luguelin', 'Santos', 'Dominican', 'Monte Plata', '12-Nov-92');
INSERT INTO PARTICIPANT values(46, 'Lalonde', 'Gordon', 'Trinidad', 'Lowlands', '25-Nov-88');
INSERT INTO PARTICIPANT values(47, 'Chris', 'Brown', 'Bahamian', 'Eleuthera', '15-Oct-78');
INSERT INTO PARTICIPANT values(48, 'Kevin', 'Borlee', 'Belgian', 'Woluwe-Saint-Lambert', '22-Feb-88');
INSERT INTO PARTICIPANT values(49, 'Jonathan', 'Borlee', 'Belgian', 'Woluwe-Saint-Lambert', '22-Feb-88');
INSERT INTO PARTICIPANT values(50, 'Demetrius', 'Pinder', 'Bahamian', 'Grand Bahama', '13-Feb-89');
INSERT INTO PARTICIPANT values(51, 'Steven', 'Solomon', 'Australian', 'Vacluse', '16-May-93');
INSERT INTO PARTICIPANT values(52, 'Eric ', 'Wang', 'American', 'Toledo', '15-Aug-65');
INSERT INTO PARTICIPANT values(53, 'Brett', 'Zatlin', 'American', 'Norfolk', '05-Sep-60');
INSERT INTO PARTICIPANT values(54, 'Joe', 'Ellis', 'American', 'Aurora', '11-Feb-67');
INSERT INTO PARTICIPANT values(55, 'Ben ', 'Walsh', 'American', 'Boston', '12-Feb-67');
INSERT INTO PARTICIPANT values(56, 'Blair', 'Barstar', 'American', 'North Hempstead', '26-Nov-67');
INSERT INTO PARTICIPANT values(57, 'Andrew ', 'Schuck', 'American', 'Chesapeake', '30-Aug-71');
INSERT INTO PARTICIPANT values(58, 'Thomas', 'Brisbane', 'American', 'New Orleans', '05-May-72');
INSERT INTO PARTICIPANT values(59, 'Elise', 'Claffey', 'American', 'Toledo', '22-Sep-73');
INSERT INTO PARTICIPANT values(60, 'Leslie', 'Djhone', 'French', 'Abidjan', '18-Mar-81');
INSERT INTO PARTICIPANT values(61, 'Martyn', 'Rooney', 'British', 'Croydon', '03-Apr-87');
INSERT INTO PARTICIPANT values(62, 'Renny', 'Quow', 'Trinidad', 'Tobago', '25-Aug-87');
INSERT INTO PARTICIPANT values(63, 'Johan', 'Wissman', 'Swedish', 'Helsingborg', '02-Nov-82');
INSERT INTO PARTICIPANT values(64, 'David', 'Neville', 'American', 'Merrillville', '01-Jun-84');
INSERT INTO PARTICIPANT values(65, 'Sarah', 'Merriwether', 'American', 'Fort Wayne', '22-Sep-73');
INSERT INTO PARTICIPANT values(66, 'Mia', 'Cheslock', 'American', 'Chandler', '15-Dec-73');
INSERT INTO PARTICIPANT values(67, 'Kevin', 'Raftery', 'American', 'Stockton', '12-Mar-75');
INSERT INTO PARTICIPANT values(68, 'Josh', 'Spiess', 'American', 'Henderson', '21-Aug-77');
INSERT INTO PARTICIPANT values(69, 'Crosby', 'Spiess', 'American', 'Anaheim', '05-Sep-60');
INSERT INTO PARTICIPANT values(70, 'Pokemon', 'Gordon', 'American', 'Pittsburgh', '10-Apr-42');
INSERT INTO PARTICIPANT values(71, 'Otis', 'Harris', 'American', 'Edwards', '30-Jun-82');
INSERT INTO PARTICIPANT values(72, 'Derrick', 'Brew', 'American', 'Houston', '28-Dec-77');
INSERT INTO PARTICIPANT values(73, 'Alleyne', 'Francique', 'Grenada', 'St. Andrews', '07-Jun-76');
INSERT INTO PARTICIPANT values(74, 'Brandon', 'Simpson', 'Jamaican', 'Kingston', '06-Sep-81');
INSERT INTO PARTICIPANT values(75, 'Davian', 'Clarke', 'Jamican', 'Kingston', '30-Apr-76');
INSERT INTO PARTICIPANT values(76, 'Michael', 'Blackwood', 'Jamaican', 'Clarendon', '29-Aug-76');
INSERT INTO PARTICIPANT values(77, 'Lucy', 'Pepperman', 'American', 'Nashville', '21-Aug-77');
INSERT INTO PARTICIPANT values(78, 'Jack', 'Pepperman', 'American', 'Hialeah', '28-May-81');
INSERT INTO PARTICIPANT values(79, 'Gillian', 'Iacobucci', 'American', 'Chicago', '16-Oct-87');
INSERT INTO PARTICIPANT values(80, 'Emma ', 'Gray', 'American', 'Kansas City', '08-Jun-88');
INSERT INTO PARTICIPANT values(81, 'Veronica', 'Yonce', 'American', 'Anchorage', '16-May-92');
INSERT INTO PARTICIPANT values(82, 'Caroline', 'Duvivier', 'American', 'Riverside', '16-Jul-94');


INSERT INTO TEAM values(0, 3, 'USA 4x1', 1, 4, 24);
INSERT INTO TEAM values(1, 3, 'USA 4x4', 1, 5, 25);
INSERT INTO TEAM values(2, 3, 'USA Mens BBall', 1, 6, 21);
INSERT INTO TEAM values(3, 0, 'Team Wariner', 1, 1, 23);
INSERT INTO TEAM values(4, 1, 'Team Jelimo', 2, 2, 22);
INSERT INTO TEAM values(5, 2, 'Team Bolt', 0, 3, 20);
INSERT INTO TEAM values(6, 2, 'Team Blake', 0, 3, 26);
INSERT INTO TEAM values(7, 2, 'Team Gatlin', 1, 3, 27);
INSERT INTO TEAM values(8, 2, 'Team Gay', 1, 3, 28);
INSERT INTO TEAM values(9, 2, 'Team Bailey', 1, 3, 29);
INSERT INTO TEAM values(10, 3, 'Team Van Niekerk', 159, 1, 37);
INSERT INTO TEAM values(11, 3, 'Team James', 3, 1, 38);
INSERT INTO TEAM values(12, 3, 'Team Merrit', 1, 1, 39);
INSERT INTO TEAM values(13, 3, 'Team Cedenio', 4, 1, 40);
INSERT INTO TEAM values(14, 3, 'Team Sibanda', 5, 1, 41);
INSERT INTO TEAM values(15, 3, 'Team Khamis', 6, 1, 42);
INSERT INTO TEAM values(16, 3, 'Team Taplin', 3, 1, 43);
INSERT INTO TEAM values(17, 3, 'Team Hudson-Smith', 7, 1, 44);
INSERT INTO TEAM values(18, 2, 'Team Kirani', 3, 1, 52);
INSERT INTO TEAM values(19, 2, 'Team Santos', 60, 1, 53);
INSERT INTO TEAM values(20, 2, 'Team Gordon', 4, 1, 54);
INSERT INTO TEAM values(21, 2, 'Team Brown', 21, 1, 55);
INSERT INTO TEAM values(22, 2, 'Team Borlee', 25, 1, 56);
INSERT INTO TEAM values(23, 2, 'Team Borlee', 25, 1, 57);
INSERT INTO TEAM values(24, 2, 'Team Pinder', 21, 1, 58);
INSERT INTO TEAM values(25, 2, 'Team Solomon', 18, 1, 59);
INSERT INTO TEAM values(26, 1, 'Team Merritt', 1, 1, 66);
INSERT INTO TEAM values(27, 1, 'Team Wariner', 1, 1, 23);
INSERT INTO TEAM values(28, 1, 'Team Neville', 1, 1, 65);
INSERT INTO TEAM values(29, 1, 'Team Brown', 21, 1, 55);
INSERT INTO TEAM values(30, 1, 'Team Djhone', 70, 1, 70);
INSERT INTO TEAM values(31, 1, 'Team Roony', 7, 1, 67);
INSERT INTO TEAM values(32, 1, 'Team Quow', 4, 1, 68);
INSERT INTO TEAM values(33, 1, 'Team Wissman', 180, 1, 69);
INSERT INTO TEAM values(34, 0, 'Team Wariner', 1, 1, 23);
INSERT INTO TEAM values(35, 0, 'Team Harris', 1, 1, 77);
INSERT INTO TEAM values(36, 0, 'Team Brew', 1, 1, 78);
INSERT INTO TEAM values(37, 0, 'Team Francique', 3, 1, 79);
INSERT INTO TEAM values(38, 0, 'Team Simpson', 0, 1, 80);
INSERT INTO TEAM values(39, 0, 'Team Clarke', 0, 1, 81);
INSERT INTO TEAM values(40, 0, 'Team Djhone', 70, 1, 70);
INSERT INTO TEAM values(41, 0, 'Team Blackwood', 0, 1, 82);
INSERT INTO TEAM values(42, 0, 'Team Kipketer', 57, 2, null);
INSERT INTO TEAM values(43, 0, 'Team Ismail', 176, 2, null);
INSERT INTO TEAM values(44, 0, 'Team Mutua', 2, 2, null);
INSERT INTO TEAM values(45, 0, 'Team Longo', 96, 2, null);
INSERT INTO TEAM values(46, 0, 'Team Nduwimana', 24, 2, null);
INSERT INTO TEAM values(47, 0, 'Team Soos', 7, 2, null);
INSERT INTO TEAM values(48, 0, 'Team Dos Santos', 33, 2, null);
INSERT INTO TEAM values(49, 0, 'Team Johnson', 1, 2, null);


INSERT INTO TEAM_MEMBER values(0, 12);
INSERT INTO TEAM_MEMBER values(0, 13);
INSERT INTO TEAM_MEMBER values(0, 14);
INSERT INTO TEAM_MEMBER values(0, 15);
INSERT INTO TEAM_MEMBER values(0, 24);
INSERT INTO TEAM_MEMBER values(1, 16);
INSERT INTO TEAM_MEMBER values(1, 17);
INSERT INTO TEAM_MEMBER values(1, 18);
INSERT INTO TEAM_MEMBER values(1, 19);
INSERT INTO TEAM_MEMBER values(1, 25);
INSERT INTO TEAM_MEMBER values(2, 7);
INSERT INTO TEAM_MEMBER values(2, 8);
INSERT INTO TEAM_MEMBER values(2, 9);
INSERT INTO TEAM_MEMBER values(2, 10);
INSERT INTO TEAM_MEMBER values(2, 11);
INSERT INTO TEAM_MEMBER values(2, 21);
INSERT INTO TEAM_MEMBER values(3, 6);
INSERT INTO TEAM_MEMBER values(3, 23);
INSERT INTO TEAM_MEMBER values(4, 5);
INSERT INTO TEAM_MEMBER values(4, 22);
INSERT INTO TEAM_MEMBER values(5, 0);
INSERT INTO TEAM_MEMBER values(5, 20);
INSERT INTO TEAM_MEMBER values(6, 1);
INSERT INTO TEAM_MEMBER values(6, 26);
INSERT INTO TEAM_MEMBER values(7, 2);
INSERT INTO TEAM_MEMBER values(7, 27);
INSERT INTO TEAM_MEMBER values(8, 3);
INSERT INTO TEAM_MEMBER values(8, 28);
INSERT INTO TEAM_MEMBER values(9, 4);
INSERT INTO TEAM_MEMBER values(9, 29);
INSERT INTO TEAM_MEMBER values(10, 30);
INSERT INTO TEAM_MEMBER values(11, 31);
INSERT INTO TEAM_MEMBER values(12, 16);
INSERT INTO TEAM_MEMBER values(13, 32);
INSERT INTO TEAM_MEMBER values(14, 33);
INSERT INTO TEAM_MEMBER values(15, 34);
INSERT INTO TEAM_MEMBER values(16, 35);
INSERT INTO TEAM_MEMBER values(17, 36);
INSERT INTO TEAM_MEMBER values(26, 16);
INSERT INTO TEAM_MEMBER values(27, 6);
INSERT INTO TEAM_MEMBER values(28, 63);
INSERT INTO TEAM_MEMBER values(29, 47);
INSERT INTO TEAM_MEMBER values(30, 59);
INSERT INTO TEAM_MEMBER values(31, 60);
INSERT INTO TEAM_MEMBER values(32, 61);
INSERT INTO TEAM_MEMBER values(33, 62);
INSERT INTO TEAM_MEMBER values(34, 6);
INSERT INTO TEAM_MEMBER values(35, 70);
INSERT INTO TEAM_MEMBER values(36, 71);
INSERT INTO TEAM_MEMBER values(37, 72);
INSERT INTO TEAM_MEMBER values(38, 73);
INSERT INTO TEAM_MEMBER values(39, 74);
INSERT INTO TEAM_MEMBER values(40, 60);
INSERT INTO TEAM_MEMBER values(41, 75);
INSERT INTO TEAM_MEMBER values(42, 88); -- err
INSERT INTO TEAM_MEMBER values(43, 89);
INSERT INTO TEAM_MEMBER values(44, 90);
INSERT INTO TEAM_MEMBER values(45, 91);
INSERT INTO TEAM_MEMBER values(46, 92);
INSERT INTO TEAM_MEMBER values(47, 93);
INSERT INTO TEAM_MEMBER values(48, 94);
INSERT INTO TEAM_MEMBER values(49, 95);


INSERT INTO EVENT_PARTICIPATION values(4, 1, 'e');
INSERT INTO EVENT_PARTICIPATION values(5, 2, 'e');
INSERT INTO EVENT_PARTICIPATION values(1, 4, 'e');
INSERT INTO EVENT_PARTICIPATION values(3, 0, 'e');
INSERT INTO EVENT_PARTICIPATION values(2, 5, 'e');
INSERT INTO EVENT_PARTICIPATION values(2, 6, 'e');
INSERT INTO EVENT_PARTICIPATION values(2, 7, 'e');
INSERT INTO EVENT_PARTICIPATION values(2, 8, 'e');
INSERT INTO EVENT_PARTICIPATION values(2, 9, 'e');
INSERT INTO EVENT_PARTICIPATION values(6, 10, 'e');
INSERT INTO EVENT_PARTICIPATION values(6, 11, 'e');
INSERT INTO EVENT_PARTICIPATION values(6, 12, 'e');
INSERT INTO EVENT_PARTICIPATION values(6, 13, 'e');
INSERT INTO EVENT_PARTICIPATION values(6, 14, 'e');
INSERT INTO EVENT_PARTICIPATION values(6, 15, 'e');
INSERT INTO EVENT_PARTICIPATION values(6, 16, 'e');
INSERT INTO EVENT_PARTICIPATION values(6, 17, 'e');
INSERT INTO EVENT_PARTICIPATION values(7, 18, 'e');
INSERT INTO EVENT_PARTICIPATION values(7, 19, 'e');
INSERT INTO EVENT_PARTICIPATION values(7, 20, 'e');
INSERT INTO EVENT_PARTICIPATION values(7, 21, 'e');
INSERT INTO EVENT_PARTICIPATION values(7, 22, 'e');
INSERT INTO EVENT_PARTICIPATION values(7, 23, 'e');
INSERT INTO EVENT_PARTICIPATION values(7, 24, 'e');
INSERT INTO EVENT_PARTICIPATION values(7, 25, 'e');
INSERT INTO EVENT_PARTICIPATION values(8, 26, 'e');
INSERT INTO EVENT_PARTICIPATION values(8, 27, 'e');
INSERT INTO EVENT_PARTICIPATION values(8, 28, 'e');
INSERT INTO EVENT_PARTICIPATION values(8, 29, 'e');
INSERT INTO EVENT_PARTICIPATION values(8, 30, 'e');
INSERT INTO EVENT_PARTICIPATION values(8, 31, 'e');
INSERT INTO EVENT_PARTICIPATION values(8, 32, 'e');
INSERT INTO EVENT_PARTICIPATION values(8, 33, 'e');
INSERT INTO EVENT_PARTICIPATION values(9, 34, 'e');
INSERT INTO EVENT_PARTICIPATION values(9, 35, 'e');
INSERT INTO EVENT_PARTICIPATION values(9, 36, 'e');
INSERT INTO EVENT_PARTICIPATION values(9, 37, 'e');
INSERT INTO EVENT_PARTICIPATION values(9, 38, 'e');
INSERT INTO EVENT_PARTICIPATION values(9, 39, 'e');
INSERT INTO EVENT_PARTICIPATION values(9, 40, 'e');
INSERT INTO EVENT_PARTICIPATION values(9, 41, 'e');
INSERT INTO EVENT_PARTICIPATION values(10, 42, 'e');
INSERT INTO EVENT_PARTICIPATION values(10, 43, 'e');
INSERT INTO EVENT_PARTICIPATION values(10, 44, 'e');
INSERT INTO EVENT_PARTICIPATION values(10, 45, 'e');
INSERT INTO EVENT_PARTICIPATION values(10, 46, 'e');
INSERT INTO EVENT_PARTICIPATION values(10, 47, 'e');
INSERT INTO EVENT_PARTICIPATION values(10, 48, 'e');
INSERT INTO EVENT_PARTICIPATION values(10, 49, 'e');


INSERT INTO SCOREBOARD values(0, 9, 34, 6, 1, 1);
INSERT INTO SCOREBOARD values(0, 9, 35, 71, 2, 2);
INSERT INTO SCOREBOARD values(0, 9, 36, 72, 3, 3);
INSERT INTO SCOREBOARD values(0, 9, 37, 73, 4, null);
INSERT INTO SCOREBOARD values(0, 9, 38, 74, 5, null);
INSERT INTO SCOREBOARD values(0, 9, 39, 75, 6, null);
INSERT INTO SCOREBOARD values(0, 9, 40, 60, 7, null);
INSERT INTO SCOREBOARD values(0, 9, 41, 76, 8, null);
INSERT INTO SCOREBOARD values(1, 8, 26, 16, 1, 1);
INSERT INTO SCOREBOARD values(1, 8, 27, 6, 2, 2);
INSERT INTO SCOREBOARD values(1, 8, 28, 64, 3, 3);
INSERT INTO SCOREBOARD values(1, 8, 29, 47, 4, null);
INSERT INTO SCOREBOARD values(1, 8, 30, 60, 5, null);
INSERT INTO SCOREBOARD values(1, 8, 31, 61, 6, null);
INSERT INTO SCOREBOARD values(1, 8, 32, 62, 7, null);
INSERT INTO SCOREBOARD values(1, 8, 33, 63, 8, null);
INSERT INTO SCOREBOARD values(2, 7, 18, 31, 1, 1);
INSERT INTO SCOREBOARD values(2, 7, 19, 45, 2, 2);
INSERT INTO SCOREBOARD values(2, 7, 20, 46, 3, 3);
INSERT INTO SCOREBOARD values(2, 7, 21, 47, 4, null);
INSERT INTO SCOREBOARD values(2, 7, 22, 48, 5, null);
INSERT INTO SCOREBOARD values(2, 7, 23, 49, 6, null);
INSERT INTO SCOREBOARD values(2, 7, 24, 50, 7, null);
INSERT INTO SCOREBOARD values(2, 7, 25, 51, 8, null);
INSERT INTO SCOREBOARD values(3, 6, 10, 30, 1, 1);
INSERT INTO SCOREBOARD values(3, 6, 11, 31, 2, 2);
INSERT INTO SCOREBOARD values(3, 6, 12, 16, 3, 3);
INSERT INTO SCOREBOARD values(3, 6, 13, 32, 4, null);
INSERT INTO SCOREBOARD values(3, 6, 14, 33, 5, null);
INSERT INTO SCOREBOARD values(3, 6, 15, 34, 6, null);
INSERT INTO SCOREBOARD values(3, 6, 16, 35, 7, null);
INSERT INTO SCOREBOARD values(3, 6, 17, 36, 8, null);